### ISSUE TITLE
Examples 

### ISSUE THREAD

**Issue by fionabrinkman** [eringill/chronic_infection_python#3]
Thanks for sending the app for further testing! 

one possible issue: 
Why when you choose the example deer one, does it not say that it’s a zoonosis sequence as a result? Could we use one that gives such a result?

**Comment by eringill** [comment]
This is a zoonotic sample. The reason it's not giving the correct result is because the deer mutation distribution that we're comparing it against (from the Feng paper) is incorrect. Sally has contacted them, and they're corresponding with her to get the correct distribution.

**Comment by fionabrinkman** [comment]
Doh. I thought that had been dealt with - sorry about that.
