### ISSUE TITLE
One mutation enough? 

### ISSUE THREAD

**Issue by fionabrinkman** [eringill/chronic_infection_python#6]
if I enter in just one mutation, it still gives me a result. I’m not sure about this, but do you want to set some sort of minimum for how many mutations a list, or have a little warning that based on mutation this is not very reliable?

**Comment by eringill** [comment]
This relates to the power analysis that Sally conducted [here](https://docs.google.com/document/d/1uw8CFobePEK8x0zFyql3Gg3lwAaxv7At30NiaKFERvM/edit).

I don't want to get into the weeds with this, as it will be described in the associated preprint. I can add a tool-tip that says "power analyses suggest that a minimum of 10 lineage-defining mutations are needed for accurate results".
